PayrollGenerator/PayrollGenerator/Controllers/PayrollController.cs
using PayrollGenerator.Helper;
using PayrollGenerator.Models;
using System;
using System.Web.Mvc;

namespace PayrollGenerator.Controllers
{
    public class PayrollController : Controller
    {
        private readonly IPayroll payrollHelper;

        public PayrollController()
        {

        }
        public PayrollController(IPayroll payrollHelper)
        {
            this.payrollHelper = payrollHelper;
        }

        // GET: Payroll
        public ActionResult Index()
        {
            var payrollModel = new PayrollModel
            {
                FullName = string.Empty,
                Month = DateTime.Now,
                GrossIncome = 0,                
                IncomeTax = 0,
                NetIncome = 0,
                SuperFund = 0
            };
            return View(payrollModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CalculatePayroll([Bind(Include = "FirstName,LastName, Month, AnnualSalary, Super")] PayrollModel payroll)
        {
            if(ModelState.IsValid)
            {
                IPayroll payrollHelper = new Payroll(payroll.AnnualSalary);
                ISuperAnnuation superAnnuation = new SuperAnnuation(payroll.AnnualSalary, payroll.Super);

                var payrollModel = new PayrollModel
                {
                    FullName = payroll.FirstName + ' ' + payroll.LastName,
                    Month = payroll.Month,
                    Payperiod = payrollHelper.GetPayPeriod(payroll.Month),
                    GrossIncome = payrollHelper.CalculateGrossIncome(),
                    NetIncome = payrollHelper.CalcualteNetIncome(),
                    IncomeTax = payrollHelper.CaclulateIncomeTax(),
                    SuperFund = superAnnuation.CalculateSuperAnnuation()
                };

                return View("Index", payrollModel);
            }
            return View("Index");
        }

        public ActionResult Instructions()
        {
            return View();
        }

        public ActionResult Assumptions()
        {
            return View();
        }        
    }
}

PayrollGenerator/PayrollGenerator/Views/Payroll/Assumptions.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Payroll Assumptions</h1>
<ul>
    <li> Annual salary range is assumed between $1 to $500000</li>
    <li> SuperAnnuation is set between 1 to 50%</li>
    <li> The tax values given for the year 2012 -2013 is used for the tax calculation irrespective of the year selected in the payroll generator application</li>
    <li> A calender control is used in the application with the assumption that this application can be extended to calculate the payroll from the selected date to the end of the month</li>
    <li> Payroll calculation is always for the entire month</li>
</ul>

@Html.ActionLink("Go to Payroll", "Index")

PayrollGenerator/PayrollGenerator/Views/Payroll/Index.cshtml
@model PayrollGenerator.Models.PayrollModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Index";
}

<h2>Payroll Generator</h2>
@Html.ActionLink("Payroll Instructions", "Instructions") <br />
@Html.ActionLink("Assumptions", "Assumptions")
@using (Html.BeginForm("CalculatePayroll", "Payroll", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.AnnualSalary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnnualSalary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnnualSalary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Super, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Super, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Super, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Month, "", new { @class = "text-danger" })               
            </div>                       
        </div>
        <label>
            <span style="float: right; width: 115px"></span>
            <input style="margin-left: -25px " type="submit" value="Generate Payslip"/><span></span>            
            <span style="float: right; width: 260px;"></span>
        </label>       
        </div>
   }

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)                
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payperiod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GrossIncome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IncomeTax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NetIncome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SuperFund)
            </th>
            <th></th>
        </tr>

            
        <tr>
            <td>
                @Html.DisplayFor(model => model.FullName)
            </td>
            <td>
                @Html.DisplayFor(model => model.Payperiod)
            </td>
            <td>
                @Html.DisplayFor(model => model.GrossIncome)
            </td>
            <td>
                @Html.DisplayFor(model => model.IncomeTax)
            </td>
            <td>
                @Html.DisplayFor(model => model.NetIncome)
            </td>
            <td>
                @Html.DisplayFor(model => model.SuperFund)
            </td>
        </tr>
               
    </table>

PayrollGenerator/PayrollGenerator/Views/Payroll/Instructions.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Payroll Instructions</h1>
<ul>
    <li>All fields are mandatory</li>
    <li>First and Last name should start with upper case</li>
    <li>Annual salary accepts values between $1 to $500000</li>
    <li>SuperAnnuation values should be from 1 to 50</li>
    <li>You can select any date in a calender month. However, the payroll is calculated for the entire month(i.e from start to end of the month, not from the selected date to the end of the month)</li>
</ul>

@Html.ActionLink("Go to Payroll", "Index")